config/routes.rb
Rails.application.routes.draw do
  
  scope '/models' do
    scope '/:model_slug' do

      scope '/model_types' do
        get '/' => 'modeltypes#index'
      end
      scope '/model_types_price' do
        scope '/:model_type_slug' do
          post '/' => 'modeltypes#show'
        end
      end

    end
  end
      

end

app/models/model.rb
class Model < ActiveRecord::Base
    has_many :modeltypes
    belongs_to :organization
end

app/models/modeltype.rb
class Modeltype < ActiveRecord::Base
    belongs_to :model
end

app/models/organization.rb
class Organization < ActiveRecord::Base
    has_many :models
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:name, :model_slug)
    end
end

app/controllers/modeltypes_controller.rb
class ModeltypesController < ApplicationController
  before_action :set_modeltype, only: [:show, :edit, :update, :destroy]

  # GET /modeltypes
  # GET /modeltypes.json
  def index
    @modeltypes = Modeltype.all
  end

  # GET /modeltypes/1
  # GET /modeltypes/1.json
  def show
  end

  # GET /modeltypes/new
  def new
    @modeltype = Modeltype.new
  end

  # GET /modeltypes/1/edit
  def edit
  end

  # POST /modeltypes
  # POST /modeltypes.json
  def create
    @modeltype = Modeltype.new(modeltype_params)

    respond_to do |format|
      if @modeltype.save
        format.html { redirect_to @modeltype, notice: 'Modeltype was successfully created.' }
        format.json { render :show, status: :created, location: @modeltype }
      else
        format.html { render :new }
        format.json { render json: @modeltype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modeltypes/1
  # PATCH/PUT /modeltypes/1.json
  def update
    respond_to do |format|
      if @modeltype.update(modeltype_params)
        format.html { redirect_to @modeltype, notice: 'Modeltype was successfully updated.' }
        format.json { render :show, status: :ok, location: @modeltype }
      else
        format.html { render :edit }
        format.json { render json: @modeltype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modeltypes/1
  # DELETE /modeltypes/1.json
  def destroy
    @modeltype.destroy
    respond_to do |format|
      format.html { redirect_to modeltypes_url, notice: 'Modeltype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modeltype
      @modeltype = Modeltype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modeltype_params
      params.require(:modeltype).permit(:name, :model_type_slug, :model_type_code, :integer, :base_price)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :public_name, :org_type, :pricing_policy)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/modeltypes_helper.rb
module ModeltypesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model_slug %><br>
    <%= f.text_field :model_slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.name %></td>
        <td><%= model.model_slug %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_model_path(model) %></td>
        <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @model.name %>
</p>

<p>
  <strong>Model slug:</strong>
  <%= @model.model_slug %>
</p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>

app/views/modeltypes/_form.html.erb
<%= form_for(@modeltype) do |f| %>
  <% if @modeltype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modeltype.errors.count, "error") %> prohibited this modeltype from being saved:</h2>

      <ul>
      <% @modeltype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :model_id %><br>
    <%= f.number_field :model_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model_type_slug %><br>
    <%= f.text_field :model_type_slug %>
  </div>
  <div class="field">
    <%= f.label :model_type_code %><br>
    <%= f.text_field :model_type_code %>
  </div>
  <div class="field">
    <%= f.label :base_price %><br>
    <%= f.number_field :base_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modeltypes/edit.html.erb
<h1>Editing Modeltype</h1>

<%= render 'form' %>

<%= link_to 'Show', @modeltype %> |
<%= link_to 'Back', modeltypes_path %>

app/views/modeltypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Modeltypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model type slug</th>
      <th>Model type code</th>
      <th>Integer</th>
      <th>Base price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modeltypes.each do |modeltype| %>
      <tr>
        <td><%= modeltype.name %></td>
        <td><%= modeltype.model_type_slug %></td>
        <td><%= modeltype.model_type_code %></td>
        <td><%= modeltype.base_price %></td>
        <td><%= link_to 'Show', modeltype %></td>
        <td><%= link_to 'Edit', edit_modeltype_path(modeltype) %></td>
        <td><%= link_to 'Destroy', modeltype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modeltype', new_modeltype_path %>

app/views/modeltypes/new.html.erb
<h1>New Modeltype</h1>

<%= render 'form' %>

<%= link_to 'Back', modeltypes_path %>

app/views/modeltypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @modeltype.name %>
</p>

<p>
  <strong>Model type slug:</strong>
  <%= @modeltype.model_type_slug %>
</p>

<p>
  <strong>Model type code:</strong>
  <%= @modeltype.model_type_code %>
</p>

<p>
  <strong>Base price:</strong>
  <%= @modeltype.base_price %>
</p>

<%= link_to 'Edit', edit_modeltype_path(@modeltype) %> |
<%= link_to 'Back', modeltypes_path %>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :public_name %><br>
    <%= f.text_field :public_name %>
  </div>
  <div class="field">
    <%= f.label :org_type %><br>
    <%= f.text_field :org_type %>
  </div>
  <div class="field">
    <%= f.label :pricing_policy %><br>
    <%= f.text_field :pricing_policy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Public name</th>
      <th>Type</th>
      <th>Pricing policy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.public_name %></td>
        <td><%= organization.org_type %></td>
        <td><%= organization.pricing_policy %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Public name:</strong>
  <%= @organization.public_name %>
</p>

<p>
  <strong>Org Type:</strong>
  <%= @organization.org_type %>
</p>

<p>
  <strong>Pricing policy:</strong>
  <%= @organization.pricing_policy %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>